"""
ConfBridge configuration generator
"""
import os
import logging
import subprocess
from typing import List
from database import ConferenceRoom

logger = logging.getLogger(__name__)

CONFBRIDGE_CONFIG_PATH = "/etc/asterisk/custom/confbridge.conf"


def generate_confbridge_config(rooms: List[ConferenceRoom]) -> str:
    config = "; Auto-generated ConfBridge configuration\n; Generated by Asterisk PBX GUI\n\n[general]\n\n"

    for room in rooms:
        if not room.enabled:
            continue
        config += f"[room-{room.id}]\n"
        config += "type=bridge\n"
        config += f"max_members={room.max_participants or 20}\n\n"

        config += f"[user-{room.id}]\n"
        config += "type=user\n"
        config += "music_on_hold_when_empty=yes\n"
        config += "announce_user_count=yes\n"
        config += "wait_marked=no\n"
        config += "end_marked=no\n\n"

        config += f"[admin-{room.id}]\n"
        config += "type=user\n"
        config += "admin=yes\n"
        config += "marked=yes\n"
        config += "music_on_hold_when_empty=yes\n"
        config += "announce_user_count=yes\n\n"

    return config


def write_confbridge_config(rooms: List[ConferenceRoom]) -> bool:
    try:
        config_content = generate_confbridge_config(rooms)
        os.makedirs(os.path.dirname(CONFBRIDGE_CONFIG_PATH), exist_ok=True)
        with open(CONFBRIDGE_CONFIG_PATH, 'w') as f:
            f.write(config_content)
        logger.info(f"ConfBridge config written with {len(rooms)} rooms")
        return True
    except Exception as e:
        logger.error(f"Failed to write ConfBridge config: {e}")
        return False


def reload_confbridge() -> bool:
    try:
        result = subprocess.run(
            ['docker', 'exec', 'pbx_asterisk', 'sh', '-c',
             'cp /etc/asterisk/custom/confbridge.conf /etc/asterisk/confbridge.conf && asterisk -rx "module reload app_confbridge.so"'],
            capture_output=True,
            text=True,
            timeout=10
        )

        if result.returncode == 0:
            logger.info("ConfBridge reloaded successfully")
            return True
        else:
            logger.error(f"ConfBridge reload failed: {result.stderr}")
            return False
    except Exception as e:
        logger.error(f"Failed to reload ConfBridge: {e}")
        return False
